pt:
  languageName: "Português"
  languageCode: "pt-BR"
  weight: 1
  title: "AER/ITA - Divisão de Engenharia Aeronáutica e Aeroespacial"
  params:
    description: "Divisão de Engenharia Aeronáutica e Aeroespacial do Instituto Tecnológico de Aeronáutica"

en:
  languageName: "English"
  languageCode: "en-US"
  weight: 2
  title: "AER/ITA - Division of Aeronautical and Aerospace Engineering"
  params:
    description: "Division of Aeronautical and Aerospace Engineering at the Technological Institute of Aeronautics"
