main:
  - identifier: "home"
    name: "Início"
    url: "/"
    weight: 1

  # Menu "A Divisão" - Informações institucionais
  - identifier: "divisao"
    name: "A Divisão"
    url: "#"
    weight: 2

  - identifier: "sobre"
    name: "Sobre"
    parent: "divisao"
    url: "/sobre/"
    weight: 1

  - identifier: "departamentos"
    name: "Departamentos"
    parent: "divisao"
    url: "/departamentos/"
    weight: 2


  # Pessoal - Link direto
  - identifier: "pessoal"
    name: "Pessoal"
    url: "/pessoal/"
    weight: 3

  # Menu "Pesquisa" - Produção científica e laboratorial
  - identifier: "pesquisa"
    name: "Pesquisa"
    url: "#"
    weight: 4

  - identifier: "linhas"
    name: "Linhas de Pesquisa"
    parent: "pesquisa"
    url: "/linhas/"
    weight: 1

  - identifier: "projetos"
    name: "Projetos"
    parent: "pesquisa"
    url: "/projetos/"
    weight: 2

  - identifier: "publicacoes"
    name: "Publicações"
    parent: "pesquisa"
    url: "/publicacoes/"
    weight: 3

  # Laboratórios - Link direto
  - identifier: "laboratorios"
    name: "Laboratórios"
    url: "/laboratorios/"
    weight: 5

  # Menu "Graduação"
  - identifier: "graduacao"
    name: "Graduação"
    url: "#"
    weight: 6

  - identifier: "cursos-grad"
    name: "Cursos"
    parent: "graduacao"
    url: "/graduacao/"
    weight: 1

  - identifier: "tgs"
    name: "Trabalhos de Graduação"
    parent: "graduacao"
    url: "/tgs/"
    weight: 3

  # Menu "Pós-Graduação"
  - identifier: "posgraduacao"
    name: "Pós-Graduação"
    url: "#"
    weight: 7

  - identifier: "pg-cursos"
    name: "Cursos"
    parent: "posgraduacao"
    url: "/posgraduacao/"
    weight: 1

  - identifier: "teses"
    name: "Dissertações e Teses"
    parent: "posgraduacao"
    url: "/teses/"
    weight: 2

  # Contato - Link direto
  - identifier: "contato"
    name: "Contato"
    url: "/contato/"
    weight: 9

  - identifier: "documentos"
    name: "Horários e documentos"
    url: "/documentos/"
    weight: 8
